const MESSAGES = {
	COMMANDS : {
		ADMIN : {
			EMOJIS: {
				name: "emojis",
				aliases: ["emolist"],
				category: "admin",
				description: "Renvoit la liste des émojis du serveur.",
				cooldown: 10,
				usage: "",
				permissions: true,
				args: false,
			},
			EXIT: {
				name: "exit",
				aliases: ["éteindre"],
				category: "admin",
				description: "Éteint le bot",
				cooldown: 10,
				usage: "",
				permissions: true,
				args: false,
			},
			NICKS: {
				name: "nicks",
				aliases: ["resetnicks"],
				category: "admin",
				description: "Reset les pseudos de tous les joueurs sur le serveur.",
				cooldown: 10,
				usage: "",
				permissions: true,
				args: false,
			},
			RELOAD: {
				name: "reload",
				aliases: ["rc"],
				category: "admin",
				description: "Actualise une cmd.",
				cooldown: 10,
				usage: "<command_name>",
				permissions: true,
				args: true,
			},
			SERVERS: {
				name: "servers",
				aliases: [""],
				category: "admin",
				description: "Renvoit la liste des serveurs sur lesquels est le BOT.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			SPAM : {
				name: "spam",
				aliases: [""],
				category: "admin",
				description: "Spam en MP un message.",
				cooldown: 10,
				usage: "<@user> <message>",
				permissions: false,
				args: false,
			},
		},
		MISC : {
			HELP: {
				name: "help",
				aliases: ["aide"],
				category: "misc",
				description: "Rnvoit la page d'aide.",
				cooldown: 10,
				usage: "<commande_name>",
				permissions: false,
				args: false,
			},
			PING: {
				name: "ping",
				aliases: ["pong"],
				category: "misc",
				description: "Renvoit le ping du message et du serveur.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			SAY: {
				name: "say",
				aliases: ["rep"],
				category: "misc",
				description: "Répète votre texte.",
				cooldown: 10,
				usage: "<votre_message>",
				permissions: false,
				args: false,
			},
		},
		MODERATION : {
			BAN: {
				name: "ban",
				aliases: ["bannir"],
				category: "moderation",
				description: "Bannit un utilisateur.",
				cooldown: 10,
				usage: "<@user> <raison>",
				permissions: false,
				args: true,
			},
			KICK: {
				name: "kick",
				aliases: ["expulser"],
				category: "moderation",
				description: "Expulse un utilisateur.",
				cooldown: 10,
				usage: "<@user> <raison>",
				permissions: false,
				args: true,
			},
			MUTE: {
				name: "mute",
				aliases: ["taire"],
				category: "moderation",
				description: "Enlève le droit de parole à un utilisateur.",
				cooldown: 10,
				usage: "<@user> <time> <raison>",
				permissions: false,
				args: true,
			},
			PRUNE: {
				name: "prune",
				aliases: ["clearuser"],
				category: "moderation",
				description: "Supprime un nombre de message spécifique d'un utilisateur.",
				cooldown: 10,
				usage: "<@user> <nbr_msg>",
				permissions: false,
				args: true,
			},
			PURGE: {
				name: "purge",
				aliases: ["clear"],
				category: "moderation",
				description: "Supprime un nombre de message spécifique.",
				cooldown: 10,
				usage: "<nbr_msg>",
				permissions: false,
				args: true,
			},
			UNBAN: {
				name: "unban",
				aliases: ["deban"],
				category: "moderation",
				description: "Dé-bannit un utilisateur.",
				cooldown: 10,
				usage: "<id_user>",
				permissions: false,
				args: true,
			},
			UNMUTE: {
				name: "unmute",
				aliases: ["demute"],
				category: "moderation",
				description: "Rends le droit de parole à un utilisateur.",
				cooldown: 10,
				usage: "<@user>",
				permissions: false,
				args: true,
			},
		},
		NATIONSGLORY: {
			HEAD: {
				name: "head",
				aliases: ["tête"],
				category: "nationsglory",
				description: "Renvoit la tête d'un joueur en 3D.",
				cooldown: 10,
				usage: "<pseudo>",
				permissions: false,
				args: true,
			},
			PINGNG: {
				name: "pingng",
				aliases: ["pongng"],
				category: "nationsglory",
				description: "Renvoit le nombre d'utilisateurs connectés sur NG.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			RADIO: {
				name: "radio",
				aliases: ["ngradio"],
				category: "nationsglory",
				description: "Lance NG-Radio..",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			SKIN: {
				name: "skin",
				aliases: ["corps"],
				category: "nationsglory",
				description: "Renvoit le corps d'un utilisateur.",
				cooldown: 10,
				usage: "<pseudo>",
				permissions: false,
				args: false,
			},
			STOP: {
				name: "stop",
				aliases: ["ngstop"],
				category: "nationsglory",
				description: "Stoppe NG-Radio.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			UNDERPOWER: {
				name: "underPower",
				aliases: ["up"],
				category: "nationsglory",
				description: "Renvoit la liste des pays en sous-power",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
		},
		UTILITAIRES : {
			INFOBOT: {
				name: "infobot",
				aliases: ["infobot"],
				category: "utilitaires",
				description: "Donne des infos sur le BOT.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
      PLAY: {
				name: "play",
				aliases: ["p"],
				category: "utilitaires",
				description: "joue une musique",
				cooldown: 10,
				usage: "<musique>",
				permissions: false,
				args: false,
			},
			INFOUSER: {
				name: "infouser",
				aliases: ["infosuer"],
				category: "utilitaires",
				description: "Donne des infso sur un utilisateur.",
				cooldown: 10,
				usage: "<@user>",
				permissions: false,
				args: false,
			},
			INFOSERV: {
				name: "infoserv",
				aliases: ["infoserverv"],
				category: "utilitaires",
				description: "Donne des infos sur le serv.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			STATS: {
				name: "stats",
				aliases: ["rep"],
				category: "utilitaires",
				description: "Envoit des stats.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			POLL: {
				name: "poll",
				aliases: ["sondage"],
				category: "utilitaires",
				description: "Renvoit un saondage;",
				cooldown: 10,
				usage: "<sondage>",
				permissions: false,
				args: true,
			},
			AVATAR: {
				name: "avatar",
				aliases: ["pp"],
				category: "utilitaires",
				description: "Renvoit une photo de profil discord.",
				cooldown: 10,
				usage: "<null>/<@user>",
				permissions: false,
				args: false,
			},
			ICON: {
				name: "icon",
				aliases: ["icône"],
				category: "utilitaires",
				description: "Renvoit une photo de profil d'un serveur discord.",
				cooldown: 10,
				usage: "<guild_id>",
				permissions: false,
				args: false,
			},
			BOTINFO: {
				name: "botinfo",
				aliases: ["botinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur le BOT.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			SERVERINFO: {
				name: "serverinfo",
				aliases: ["servinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur le serveur.",
				cooldown: 10,
				usage: "<country_name>",
				permissions: false,
				args: false,
			},
			SUGG: {
				name: "sugg",
				aliases: ["idea"],
				category: "utilitaires",
				description: "Propose une suggestion.",
				cooldown: 10,
				usage: "<suggestion>",
				permissions: false,
				args: true,
			},
			TEAM: {
				name: "team",
				aliases: ["ekip"],
				category: "utilitaires",
				description: "Présente la team.",
				cooldown: 10,
				usage: "<TEAM>",
				permissions: false,
				args: false,
			},
			USERINFO: {
				name: "userinfo",
				aliases: ["userinfo"],
				category: "utilitaires",
				description: "Renvoit des infos sur un utilisateurs.",
				cooldown: 10,
				usage: "<@user>",
				permissions: false,
				args: false,
			},
			SEND: {
				name: "send",
				aliases: ["mp", "envoyer"],
				category: "utilitaires",
				description: "Envoit un MP à la personne souhaité",
				cooldown: 10,
				usage: "<@user>",
				permissions: false,
				args: true,
			},
		},
		CONNECTIONS : {
			INSTA: {
				name: "insta",
				aliases: ["instagram"],
				category: "connections",
				description: "Renvoit un compte insta.",
				cooldown: 10,
				usage: "<pseudo>",
				permissions: false,
				args: true,
			},
			INVITE: {
				name: "invite",
				aliases: ["invitation"],
				category: "connections",
				description: "Renvoit le lien d'dinvitation du BOT.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			MC: {
				name: "mc",
				aliases: ["minecraft"],
				category: "connections",
				description: "Permet de savoir si un serveur est connecté.",
				cooldown: 10,
				usage: "<server>",
				permissions: false,
				args: true,
			},
		},
		FUNNY : {
			EIGHTBALL: {
				name: "8ball",
				aliases: ["question", "8"],
				category: "funny",
				description: "Réponds à une question.",
				cooldown: 10,
				usage: "<question ?>",
				permissions: false,
				args: false,
			},
			EMOTE: {
				name: "emote",
				aliases: ["emoji"],
				category: "funny",
				description: "Renvoi un emote de n'importe quel server ou est le bot",
				cooldown: 10,
				usage: "<emoji>",
				permissions: false,
				args: true,
			},
			LOVE: {
				name: "love",
				aliases: ["amour"],
				category: "funny",
				description: "Permet de connaître notre compatibilité.",
				cooldown: 10,
				usage: "<@user>",
				permissions: false,
				args: true,
			},
		},
		IMAGE : {
			MEME: {
				name: "meme",
				aliases: ["image"],
				category: "funny",
				description: "Renvoit un mème.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			CAT: {
				name: "cat",
				aliases: ["chat"],
				category: "image",
				description: "Renvoit une image de chat.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			DOG: {
				name: "dog",
				aliases: ["chien"],
				category: "image",
				description: "Renvoit une image de chien.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			FOX: {
				name: "fox",
				aliases: ["renard"],
				category: "image",
				description: "Renvoit une image de renard.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
			ANIMEME: {
				name: "animeme",
				aliases: ["meme"],
				category: "image",
				description: "Renvoit un mème.",
				cooldown: 10,
				usage: "",
				permissions: false,
				args: false,
			},
		},
	},
};
exports.MESSAGES = MESSAGES;